# _config.yml

# Define the source and destination directories
source: docs
destination: docs/_site

# Specify the theme
theme: jekyll-theme-primer

# Other basic configurations
title: My Jekyll Site
description: A description of my site